export default {
    products: [
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category: 'Shirts',
            image:'C:\Users\akaam\Desktop\New folder (2)\jsamazona\frontend\src\images\data.js',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category: 'Shirts',
            image:'C:\Users\akaam\Desktop\New folder (2)\jsamazona\frontend\src\images\data.js',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category: 'Shirts',
            image:'C:\Users\akaam\Desktop\New folder (2)\jsamazona\frontend\src\images\data.js',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category: 'Shirts',
            image:'C:\Users\akaam\Desktop\New folder (2)\jsamazona\frontend\src\images\data.js',
            price: 70,
            brand: 'Hiskywin',
            rating: 5,
            numReviews: 51,
            countInStock: 6,
        },
        {
            _id:'1',
            name:'Full Zip Running Shirts',
            category: 'Shirts',
            image:'C:\Users\akaam\Desktop\New folder (2)\jsamazona\frontend\src\images\data.js',
            price: 60,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
    ],
};